site_name: EDAC.dev
site_author: Derek Kaser
site_url: https://edac.dev

repo_url: https://github.com/dkaser/edac-dev
repo_name: dkaser/edac-dev

watch:
  - include

plugins:
  - search
  - git-revision-date-localized
  - glightbox
  - social

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.snippets:
      check_paths: true
  - toc:
      permalink: true

theme:
  name: material
  icon:
    repo: fontawesome/brands/github-alt
  palette:
    primary: deep purple
    accent: deep purple

nav:
  - Home: index.md
  - Unraid:
      - Experiments:
          - BTRFS/XFS Flash Drive: unraid/experiments/alternate-fs.md
          - Booting from Virtual SCSI: unraid/experiments/boot-virtio-scsi.md
      - Security:
          - CVE-2025-29266: security/CVE-2025-29266.md
      - Tailscale:
          - Plugin Setup: unraid/tailscale/plugin.md
          - Advanced Settings: unraid/tailscale/advanced.md
          - Docker Containers:
             - Options: unraid/tailscale/docker-options.md
             - TSDProxy: unraid/tailscale/docker-tsdproxy.md
             - Sidecar Container: unraid/tailscale/docker-sidecar.md
             - LinuxServer.io Mod: unraid/tailscale/docker-lsio.md